// Generated by scripts/build-bank.mjs from docs/rules and docs/shapes.
// Edit those files, not this one.

export type Family = 'common' | 'fable' | 'opus' | 'sonnet' | 'haiku'
export type Rule = { id: string; text: string }
export type Shape = { name: string; summary: string; fields: string; context: string; before: string; after: string }

export const RULES: Record<Family, readonly Rule[]> = {
  "common": [
    {
      "id": "keep-intent",
      "text": "Keep what the user asked for. Do not add tasks, change the goal, or answer the prompt yourself. Resolve references to the conversation (\"the second item above\", \"that file\", \"same as before\") into the concrete names they point to, and invent nothing the conversation does not show: no file names, numbers, deadlines or requirements."
    },
    {
      "id": "give-the-reason",
      "text": "When the conversation or the prompt shows why the user wants this or who it is for, say it in one plain sentence. If the reason is not knowable, leave it out rather than guess."
    },
    {
      "id": "name-the-deliverable",
      "text": "Make the output explicit: what should exist or be answered when Claude is done, and how the user will tell it is done (tests pass, a file exists, a question answered). Use a short numbered list only when the order of steps matters."
    },
    {
      "id": "question-stays-a-question",
      "text": "If the user is asking a question, describing a problem or thinking out loud, the rewrite asks for an assessment and says not to change anything yet. Never turn a question into an order to fix."
    },
    {
      "id": "state-what-is-out",
      "text": "When the prompt or conversation makes clear what must not be touched, say it in one sentence (files, behaviour, scope). Do not invent restrictions."
    },
    {
      "id": "ideas-mean-ideas",
      "text": "If the user asks for ideas, options or a plan, the rewrite asks for that and says to wait before building anything."
    },
    {
      "id": "no-reasoning-echo",
      "text": "Never ask Claude to show, write out or explain its thinking or reasoning, and never add \"think step by step\". Recent models may refuse such requests (the reasoning_extraction category). Asking for a short explanation of the answer is fine."
    },
    {
      "id": "calm-language",
      "text": "No capital-letter emphasis, no \"CRITICAL\" or \"MUST\", no threats or bribes, no urgency. Current models follow plain instructions and over-apply shouted ones."
    },
    {
      "id": "no-role-filler",
      "text": "Do not open with a role (\"You are an expert ...\"). The prompt is a user turn inside Claude Code, which already has its system prompt; a role line there only adds length."
    },
    {
      "id": "stay-short",
      "text": "The rewrite is at most twice the length of the original or 60 words, whichever is more, and never more than 180 words. Write it in the user's language and voice, first person, as if they had typed it carefully. No headings, no XML tags, no preamble."
    }
  ],
  "fable": [
    {
      "id": "fable-brief-is-enough",
      "text": "Prefer one short instruction over a list of cases. Fable follows brief instructions well and over-prescriptive prompts can make its output worse."
    },
    {
      "id": "fable-ask-for-updates",
      "text": "If the task is long and the user wants to follow along, ask for a line before starting and a short recap at the end. Fable 5.1 writes few updates between tool calls unless asked. Do not ask it to keep updates brief."
    },
    {
      "id": "fable-ambiguity",
      "text": "Where the request can be read two ways and the conversation does not settle it, ask Claude to take the most direct reading and state that assumption, rather than build for both."
    },
    {
      "id": "fable-bug-phrasing",
      "text": "Turn \"does this compile?\" into \"are there any bugs in this?\". The compile-check phrasing trips safety classifiers more often."
    }
  ],
  "opus": [
    {
      "id": "opus-no-verify-step",
      "text": "Do not add \"verify your work\" or \"add a final verification step\". Opus 5 verifies on its own and extra verification instructions waste tokens."
    },
    {
      "id": "opus-hold-scope",
      "text": "For a narrow task, say plainly to deliver what was asked at that scope and to mention, not do, anything beyond it. Opus 5 can widen a task on its own."
    },
    {
      "id": "opus-length",
      "text": "If the user wants a document or reply of a certain size, say so. Opus 5 writes longer replies and documents by default, and effort does not reliably shorten them."
    }
  ],
  "sonnet": [
    {
      "id": "sonnet-literal-scope",
      "text": "Spell out how far an instruction reaches (\"every file under src/, not just this one\"). Sonnet 5 reads prompts literally and does not generalise an instruction from one item to the rest."
    },
    {
      "id": "sonnet-no-extras",
      "text": "When the user wants only the change itself, say not to add tests, docs or files that were not asked for. Sonnet 5.5 tends to add them."
    }
  ],
  "haiku": [
    {
      "id": "haiku-run-a-check",
      "text": "For a code change that can be run, built or type-checked, ask for a real check (the tests, the type-checker, the build) before calling it done. Haiku 5.5 at low effort sometimes reports a change as done without checking it."
    }
  ]
}

export const SHAPES: readonly Shape[] = [
  {
    "name": "fix",
    "summary": "Something is broken and should work again.",
    "fields": "what goes wrong and where it shows, what should happen instead, what must stay as it is, how to tell it is fixed.",
    "context": "the last test run showed test_login_redirect failing after the session refactor in auth/session.py.",
    "before": "login broken again after your change, fix",
    "after": "test_login_redirect started failing after the session refactor in auth/session.py. Find out why and fix it so a correct password lands on the dashboard again. Keep the refactor's new structure. Done when test_login_redirect and the rest of the auth tests pass."
  },
  {
    "name": "investigate",
    "summary": "Find out why something happens, without changing it yet.",
    "fields": "the observation, where to look, what a useful answer looks like, a clear note that nothing should change yet.",
    "context": "the user pasted a chart showing nightly job runtime going from 4 to 19 minutes on 2 October.",
    "before": "why is the nightly thing so slow now",
    "after": "The nightly job went from about 4 to 19 minutes on 2 October. Find out what changed around then that explains it and tell me the likely cause with the evidence. Don't change any code yet; I want the diagnosis first."
  },
  {
    "name": "build",
    "summary": "Add something new.",
    "fields": "what it does for whom, where it lives, inputs and outputs, what is out of scope, how to tell it works.",
    "context": "the project is a FastAPI service; the user has been discussing exporting reports.",
    "before": "add csv export for reports",
    "after": "Add a CSV export for reports so analysts can open them in a spreadsheet: a GET endpoint next to the existing report routes that returns the same rows as the JSON report, one column per field. No new dependencies. Done when a test downloads a report as CSV and checks its header and row count."
  },
  {
    "name": "refactor",
    "summary": "Change how code is organised without changing what it does.",
    "fields": "the code in question, the target structure, the reason, the behaviour that must not change, how to check that.",
    "context": "the conversation showed billing.py at 1,400 lines with tax, invoice and discount logic mixed together.",
    "before": "split up billing its a mess",
    "after": "Split billing.py (about 1,400 lines) into separate modules for tax, invoices and discounts, so each can be changed without reading the others. Behaviour must stay exactly the same: no renamed public functions, no logic changes. Done when the existing billing tests pass unchanged."
  },
  {
    "name": "research",
    "summary": "Learn something from outside the codebase.",
    "fields": "the question, why it matters here, what sources count, the form of the answer.",
    "context": "the team is choosing a queue for a Python service and already runs Redis.",
    "before": "celery vs rq which one",
    "after": "We need a task queue for our Python service and already run Redis. Compare Celery and RQ for that setup: setup effort, retries and scheduling, monitoring, and how actively each is maintained. Give me a recommendation with the two or three reasons that decide it, and link your sources."
  },
  {
    "name": "review",
    "summary": "Look over work and report problems.",
    "fields": "what to review, what kind of problems matter, what to leave alone, the form of the findings.",
    "context": "the user just finished a branch adding rate limiting to the API gateway.",
    "before": "review my changes",
    "after": "Review the rate limiting changes on this branch for bugs: wrong limits, race conditions, requests that slip through, and errors that would reach users. Skip style and naming. List each finding with the file and line and why it is a problem, most serious first. Don't change the code."
  },
  {
    "name": "write",
    "summary": "Produce prose: docs, a message, a description.",
    "fields": "who reads it, what they should do or know after, length, tone, what it must include.",
    "context": "the conversation just merged a migration that renames the users table to accounts.",
    "before": "write something for the team about the migration",
    "after": "Write a short Slack message for the backend team about the migration we just merged that renames the users table to accounts. They need to know what breaks in their local setups and the one command to fix it. Five sentences at most, plain tone."
  },
  {
    "name": "ask",
    "summary": "A question that wants an answer, not a change.",
    "fields": "the question, the context it is about, how deep the answer should go.",
    "context": "the conversation has been about a React app using useEffect for data fetching.",
    "before": "is useeffect fine for this or no",
    "after": "Is useEffect a reasonable way to fetch the dashboard data in this app, or would a data-fetching library serve better here? Give me a short answer with the main trade-off; don't change anything."
  }
]
