// Turns docs/rules/*.md and docs/shapes/*.md into hooks/bank.ts. A mod has no
// file access at run time, so the plugin ships this generated copy.
// node scripts/build-bank.mjs          write hooks/bank.ts
// node scripts/build-bank.mjs --check  exit 1 if hooks/bank.ts is stale
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const FAMILIES = ['common', 'fable', 'opus', 'sonnet', 'haiku']
const SHAPES = ['fix', 'investigate', 'build', 'refactor', 'research', 'review', 'write', 'ask']

function rules(family) {
  const md = readFileSync(join(root, 'docs/rules', `${family}.md`), 'utf8')
  return md.split(/^## /m).slice(1).map(block => {
    const [head, ...rest] = block.trim().split('\n')
    const source = rest.find(l => l.startsWith('Source:'))
    const text = rest.filter(l => !l.startsWith('Source:')).join(' ').trim()
    if (!text || !source) throw new Error(`${family}.md: rule ${head} needs a text and a Source: line`)
    return { id: head.trim(), text }
  })
}

function shape(name) {
  const md = readFileSync(join(root, 'docs/shapes', `${name}.md`), 'utf8')
  const lines = md.trim().split('\n')
  const field = key => {
    const line = lines.find(l => l.startsWith(`${key}: `))
    if (!line) throw new Error(`${name}.md: missing ${key}:`)
    return line.slice(key.length + 2).trim()
  }
  return {
    name,
    summary: lines[1].trim(),
    fields: field('Fields'),
    context: field('Context'),
    before: field('Before'),
    after: field('After'),
  }
}

const bank = {
  rules: Object.fromEntries(FAMILIES.map(f => [f, rules(f)])),
  shapes: SHAPES.map(shape),
}

const out = `// Generated by scripts/build-bank.mjs from docs/rules and docs/shapes.
// Edit those files, not this one.

export type Family = ${FAMILIES.map(f => `'${f}'`).join(' | ')}
export type Rule = { id: string; text: string }
export type Shape = { name: string; summary: string; fields: string; context: string; before: string; after: string }

export const RULES: Record<Family, readonly Rule[]> = ${JSON.stringify(bank.rules, null, 2)}

export const SHAPES: readonly Shape[] = ${JSON.stringify(bank.shapes, null, 2)}
`

const target = join(root, 'hooks/bank.ts')
if (process.argv.includes('--check')) {
  let current = ''
  try { current = readFileSync(target, 'utf8') } catch {}
  if (current !== out) {
    console.error('hooks/bank.ts is out of step with docs/; run node scripts/build-bank.mjs')
    process.exit(1)
  }
  console.log('hooks/bank.ts is up to date')
} else {
  writeFileSync(target, out)
  const n = Object.values(bank.rules).reduce((a, r) => a + r.length, 0)
  console.log(`hooks/bank.ts: ${n} rules, ${bank.shapes.length} shapes`)
}
